site_name: Physics 201
site_url: https://lhs-beane.github.io/universityphysics/

theme:
  name: material
  palette: 
    scheme: slate 
    primary: teal
    accent: purple
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  # We use the default setting (generic: false).
  # This creates <script type="math/tex"> tags that MathJax 2 loves.
  - pymdownx.arithmatex:
      generic: false

extra_javascript:
  # Load MathJax 2.7. It automatically finds the tags created above.
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
