site_name: College Physics with Calculus
site_description: Complete interactive learning environment for Phys 201.
site_author: Andrew Beane
repo_url: https://lhs-beane.github.io/universityphysics/

theme:
  name: material
  features:
    - navigation.sidebar
    - navigation.sections
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnotes
  palette:
    primary: indigo
    accent: deep purple

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Modules:
      - Week 1: week1/index.md
      - Week 2: week2/index.md
      - Week 3: week3/index.md
      - Week 4: week4/index.md
      - Week 5: week5/index.md
      - Week 6: week6/index.md
      - Week 7: week7/index.md
      - Week 8: week8/index.md

