site_name: Physics 201
# Replace with your actual username below
site_url: https://lhs-beane.github.io/universityphysics/

theme:
  name: material

# We are REMOVING the math extensions here to let the script in index.md handle it.
markdown_extensions:
  - admonition
