site_name: Physics 201
site_url: https://lhs-beane.github.io/universityphysics/

theme:
  name: material
  palette: 
    scheme: slate 
    primary: teal
    accent: purple
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  # We activate Arithmatex to protect the math
  - pymdownx.arithmatex:
      # We do NOT use 'generic: true'. 
      # This defaults to the "MathJax Legacy" format 
      # which works without any helper files.
      generic: false

extra_javascript:
  # We load the older MathJax 2.7 which automatically finds 
  # the protected math blocks created by Arithmatex.
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
