site_name: Physics 201
site_url: https://your-username.github.io/universityphysics/

theme:
  name: material

markdown_extensions:
  - admonition

# We are using the Cloud version of MathJax. 
# This does NOT require any local javascript files.
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
