site_name: Physics 201
site_url: https://lhs-beane.github.io/universityphysics/

theme:
  name: material
  palette: 
    scheme: slate 
    primary: teal
    accent: purple
  features:
    - navigation.tabs
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  # This extension finds the math symbols ($$)
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # This loads the config file we just made
  - javascripts/mathjax.js
  # This loads the actual Math engine from the web
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
